/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica6;

import javax.swing.JOptionPane;
import java.util.List;
import practica6.Biblioteca;
import practica6.Autor;
import practica6.Libro;
import practica6.Prestamo;
import practica6.Estudiante;
import practica6.Horario;
import practica6.LibroFrame;
import practica6.AutorFrame;
import practica6.EstudianteFrame;
import practica6.HorarioFrame;
import practica6.PrestamoFrame;

/**
 *
 * @author Liz
 */
public class BibliotecaFrame extends javax.swing.JFrame {
    private Biblioteca biblioteca; 
    /**
     * Creates new form Grafic
     */
    public BibliotecaFrame() {
        initComponents();
        biblioteca = Biblioteca.cargarEstado("biblioteca.dat");
        if (biblioteca == null) {
            biblioteca = new Biblioteca("Biblioteca UMSA", "Lunes-Viernes", "08:00", "18:00");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        botonListaLibros = new javax.swing.JButton();
        botonESTUDIANTE1 = new javax.swing.JButton();
        botonHORARIO1 = new javax.swing.JButton();
        botonLIBRO1 = new javax.swing.JButton();
        botonListaPrestamos = new javax.swing.JButton();
        botonListaAutores = new javax.swing.JButton();
        botonPRESTAMO = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(54, 158, 155));

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));

        jLabel1.setFont(new java.awt.Font("Sylfaen", 3, 36)); // NOI18N
        jLabel1.setText("BIBLIOTECA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(197, 197, 197))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        botonListaLibros.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        botonListaLibros.setText("LISTA DE LIBROS");
        botonListaLibros.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonListaLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListaLibrosActionPerformed(evt);
            }
        });

        botonESTUDIANTE1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        botonESTUDIANTE1.setText("ESTUDIANTE");
        botonESTUDIANTE1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonESTUDIANTE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonESTUDIANTE1ActionPerformed(evt);
            }
        });

        botonHORARIO1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        botonHORARIO1.setText("HORARIO");
        botonHORARIO1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonHORARIO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHORARIO1ActionPerformed(evt);
            }
        });

        botonLIBRO1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        botonLIBRO1.setText("LIBRO");
        botonLIBRO1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonLIBRO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLIBRO1ActionPerformed(evt);
            }
        });

        botonListaPrestamos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        botonListaPrestamos.setText("LISTA DE PRESTAMOS");
        botonListaPrestamos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonListaPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListaPrestamosActionPerformed(evt);
            }
        });

        botonListaAutores.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        botonListaAutores.setText("LISTA DE AUTORES");
        botonListaAutores.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonListaAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListaAutoresActionPerformed(evt);
            }
        });

        botonPRESTAMO.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        botonPRESTAMO.setText("PRESTAMO");
        botonPRESTAMO.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonPRESTAMO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPRESTAMOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonESTUDIANTE1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonPRESTAMO, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonLIBRO1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonHORARIO1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonListaLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonListaPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonListaAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(182, 182, 182))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonLIBRO1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonHORARIO1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonESTUDIANTE1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonPRESTAMO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonListaAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonListaPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonListaLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonListaLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListaLibrosActionPerformed
        new LibroFrame(biblioteca).setVisible(true);
        
            StringBuilder sb = new StringBuilder();
    sb.append("=== LISTA DE LIBROS ===\n\n");
    
    List<Libro> libros = biblioteca.getLibros();
    if (libros.isEmpty()) {
        sb.append("(No hay libros registrados)");
    } else {
        for (Libro l : libros) {
            sb.append("- ").append(l.getTitulo()).append(" (ISBN: ").append(l.getIsbn()).append(")\n");
        }
    }
    
    JOptionPane.showMessageDialog(this, sb.toString(), "Lista de Libros", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_botonListaLibrosActionPerformed

    private void botonESTUDIANTE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonESTUDIANTE1ActionPerformed
        new EstudianteFrame(biblioteca).setVisible(true);
    }//GEN-LAST:event_botonESTUDIANTE1ActionPerformed

    private void botonHORARIO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHORARIO1ActionPerformed
        new HorarioFrame(biblioteca).setVisible(true);
    }//GEN-LAST:event_botonHORARIO1ActionPerformed

    private void botonLIBRO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLIBRO1ActionPerformed
        new LibroFrame(biblioteca).setVisible(true);
    }//GEN-LAST:event_botonLIBRO1ActionPerformed

    private void botonListaPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListaPrestamosActionPerformed
      
            StringBuilder sb = new StringBuilder();
    sb.append("=== LISTA DE PRESTAMOS ACTIVOS ===\n\n");
    
    List<Prestamo> prestamos = biblioteca.getPrestamos();
    if (prestamos.isEmpty()) {
        sb.append("(No hay prestamos activos)");
    } else {
        for (Prestamo p : prestamos) {
            sb.append("- Libro: ").append(p.libro.getTitulo())
              .append(" | Estudiante: ").append(p.estudiante.getNombre())
              .append(" | ").append(p.fechaP).append(" → ").append(p.fechaDe).append("\n");
        }
    }
    
    JOptionPane.showMessageDialog(this, sb.toString(), "Lista de Prestamos", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_botonListaPrestamosActionPerformed

    private void botonListaAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListaAutoresActionPerformed
        
            StringBuilder sb = new StringBuilder();
    sb.append("=== LISTA DE AUTORES ===\n\n");
    
    List<Autor> autores = biblioteca.getAutores();
    if (autores.isEmpty()) {
        sb.append("(No hay autores registrados)");
    } else {
        for (Autor a : autores) {
            sb.append("- ").append(a.getNombre()).append(" (").append(a.getNacionalidad()).append(")\n");
        }
    }
    
    JOptionPane.showMessageDialog(this, sb.toString(), "Lista de Autores", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_botonListaAutoresActionPerformed

    private void botonPRESTAMOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPRESTAMOActionPerformed
        new PrestamoFrame(biblioteca).setVisible(true);
    }//GEN-LAST:event_botonPRESTAMOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BibliotecaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BibliotecaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BibliotecaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BibliotecaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BibliotecaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonESTUDIANTE1;
    private javax.swing.JButton botonHORARIO1;
    private javax.swing.JButton botonLIBRO1;
    private javax.swing.JButton botonListaAutores;
    private javax.swing.JButton botonListaLibros;
    private javax.swing.JButton botonListaPrestamos;
    private javax.swing.JButton botonPRESTAMO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
